options:
  merge-default-rules: false
rules:
  bem-depth:
    - 1
    - max-depth: 5
  border-zero:
    - 2
    - none
  brace-style:
    - 2
    - allow-single-line: false
    - style: stroustrup
  class-name-format:
    - 2
    - allow-leading-underscore: false
  clean-import-paths:
    - 2
    - filename-extension: false
    - leading-underscore: false
  empty-args:
    - 2
  empty-line-between-blocks:
    - 2
    - allow-single-line-rulesets: false
  extends-before-declarations: 2
  extends-before-mixins: 2
  function-name-format:
    - 2
    - allow-leading-underscore: false
  hex-length: 2
  hex-notation: 2
  id-name-format:
    - 2
    - allow-leading-underscore: false
    - convention: snakecase
  leading-zero:
    - 2
    - include: true
  mixin-name-format:
    - 2
    - allow-leading-underscore: false
  mixins-before-declarations: 2
  nesting-depth:
    - 2
    - max-depth: 13
  no-color-keywords: 2
  no-debug: 2
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-important: 1
  no-invalid-hex: 2
  no-mergeable-selectors: 2
  no-misspelled-properties: 2
  no-transition-all: 2
  no-vendor-prefixes: 2
  no-warn: 2
  one-declaration-per-line: 2
  placeholder-name-format:
    - 2
    - allow-leading-underscore: false
  property-sort-order:
    - 1
    - order: alphabetical
  quotes:
    - 2
    - style: single
  shorthand-values: 2
  single-line-per-selector: 2
  space-after-bang: 2
  space-after-comma: 2
  space-around-operator: 1
  space-before-bang: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 2
  trailing-semicolon: 2
  url-quotes: 2
  variable-name-format:
    - 2
    - allow-leading-underscore: false
  zero-unit: 2