branches:
  only:
    - master
    - dev
language: node_js
node_js: node
notifications:
  email:
    recipients:
      - contact@pawelski.io
script:
  - npm test
  - npm run flow
  - npm run lint
  - npm run build